name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-document:
    name: Build Document
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v7.0.1

      - name: Compile Document with TeX Live
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: 2026
          scheme: full
          run: |
            # Install Microsoft TrueType core fonts package
            apk add --no-cache msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
            # Compile using xelatex with bibliography
            latexmk -xelatex -file-line-error -halt-on-error -interaction=nonstopmode main.tex

            # Compress PDF
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=main_compressed.pdf main.pdf
            
            # Overwrite original PDF
            mv main_compressed.pdf main.pdf

      - name: Prepare Output and Create Redirect
        run: |
          mkdir dist && mv main.pdf dist/buku-ta.pdf

          # Generate the HTML redirect file
          cat << 'EOF' > dist/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=/buku-ta.pdf">
              <title>Redirecting...</title>
            </head>
            <body>
              <script>window.location.href="/buku-ta.pdf";</script>
            </body>
          </html>
          EOF

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: dist

  deploy-pages:
    name: Deploy Pages
    needs: build-document
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v6.0.0
        
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
